#!/usr/bin/env python3
"""
One-shot machine-translation of the new launch-additions UI strings into the
11 non-English locale files.

Scope: only the highly visible UI strings introduced by this feature —
SiteHeader nav, HomeLaunchVideo, HomeLaunchEvent, Resources hero, Resources
category headings/bodies, languageCountLabel, openCta. Resource item
titles/blurbs (proper-noun-heavy product names) are intentionally left as
English placeholders for the human translation team to localize per JFP's
standard process.

Translations were prepared from multilingual knowledge as a *starter pass*
to replace English placeholders. Quality should be reviewed and refined by
JFP's translation team before any locale is considered "shipped".

Run:
    python3 scripts/translate-launch-additions.py
"""

from __future__ import annotations

import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
MESSAGES = REPO / "messages"

# locale → flat-dotted-key-path → translated value
TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "Header.home": "Inicio",
        "Header.resources": "Recursos",
        "Header.menuLabel": "Menú",
        "Header.menuOpenLabel": "Abrir menú",
        "Header.menuCloseLabel": "Cerrar menú",
        "HomeLaunchVideo.eyebrow": "Ver",
        "HomeLaunchVideo.heading": "Conoce el corazón de la activación.",
        "HomeLaunchVideo.iframeTitle": "Video de lanzamiento del Mundial 2026",
        "HomeLaunchEvent.pill": "Sesión informativa en vivo",
        "HomeLaunchEvent.heading": "Recorramos juntos el conjunto de herramientas.",
        "HomeLaunchEvent.body": "Una hora. La visión completa. Escucha cómo Jesus Film Project, sus aliados y líderes ministeriales de todo el mundo están activando este momento — y sal con el plan de lanzamiento para tu región.",
        "HomeLaunchEvent.cta": "Regístrate en Zoom",
        "HomeLaunchEvent.freeCaption": "Gratis. Confirmación y enlace de acceso enviados por Zoom después de tu registro.",
        "HomeLaunchEvent.dateLabel": "Fecha",
        "HomeLaunchEvent.dateValue": "Lun, 1 jun 2026",
        "HomeLaunchEvent.timeLabel": "Hora",
        "HomeLaunchEvent.timeValue": "9:00 a. m. ET",
        "HomeLaunchEvent.durationLabel": "Duración",
        "HomeLaunchEvent.durationValue": "60 minutos",
        "HomeLaunchEvent.whereLabel": "Dónde",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Calendario de Apple",
        "HomeLaunchEvent.googleCalendar": "Google Calendar",
        "HomeLaunchEvent.toolkitLink": "Recursos del kit",
        "HomeLaunchEvent.shareLink": "Compartir enlace",
        "HomeLaunchEvent.shareSubject": "Únete a la llamada de lanzamiento del Mundial 2026",
        "HomeLaunchEvent.shareBody": "Regístrate para la llamada de lanzamiento de la Activación Mundial 2026 el lunes 1 de junio a las 9:00 a. m. ET:",
        "HomeLaunchEvent.calendarTitle": "Activación Mundial 2026 — Llamada de lanzamiento",
        "HomeLaunchEvent.calendarDescription": "Sesión informativa de Jesus Film Project sobre el kit de evangelización del Mundial 2026, la estrategia digital y cómo activar tu región.",
        "HomeLaunchEvent.calendarRegisterLabel": "Regístrate",
        "HomeLaunchEvent.calendarMeetingIdLabel": "ID de reunión",
        "Resources.eyebrow": "El kit",
        "Resources.tagline": "Cada partido, cada nación, cada alma.",
        "Resources.title": "Recursos para este momento.",
        "Resources.description": "Todo es gratis y está diseñado para los 39 días del Mundial. Toma lo que sirva a tu equipo y úsalo.",
        "Resources.categories.readyToUse.heading": "Listos para usar",
        "Resources.categories.readyToUse.body": "Copia, comparte, listo. No requieren edición — envíalos hoy mismo a buscadores y nuevos creyentes.",
        "Resources.categories.customizable.heading": "Personalizables",
        "Resources.categories.customizable.body": "Plantillas, kits de doblaje y archivos fuente — adáptalos a tu idioma, tu audiencia y tu momento.",
        "Resources.categories.physicalKits.heading": "Kits físicos",
        "Resources.categories.physicalKits.body": "Herramientas tangibles para watch parties, evangelización deportiva y equipos misioneros en terreno.",
        "Resources.languageCountLabel": "idiomas",
        "Resources.openCta": "Abrir recurso",
    },
    "fr": {
        "Header.home": "Accueil",
        "Header.resources": "Ressources",
        "Header.menuLabel": "Menu",
        "Header.menuOpenLabel": "Ouvrir le menu",
        "Header.menuCloseLabel": "Fermer le menu",
        "HomeLaunchVideo.eyebrow": "Regarder",
        "HomeLaunchVideo.heading": "Découvrez l'âme de cette activation.",
        "HomeLaunchVideo.iframeTitle": "Vidéo de lancement Coupe du Monde 2026",
        "HomeLaunchEvent.pill": "Briefing en direct",
        "HomeLaunchEvent.heading": "Découvrons ensemble la boîte à outils.",
        "HomeLaunchEvent.body": "Une heure. Toute la vision. Écoutez comment Jesus Film Project, ses partenaires et les responsables ministériels du monde entier activent ce moment — et repartez avec le plan de lancement pour votre région.",
        "HomeLaunchEvent.cta": "S'inscrire sur Zoom",
        "HomeLaunchEvent.freeCaption": "Gratuit. La confirmation et le lien de connexion sont envoyés par Zoom après votre inscription.",
        "HomeLaunchEvent.dateLabel": "Date",
        "HomeLaunchEvent.dateValue": "Lun. 1 juin 2026",
        "HomeLaunchEvent.timeLabel": "Heure",
        "HomeLaunchEvent.timeValue": "9 h 00 ET",
        "HomeLaunchEvent.durationLabel": "Durée",
        "HomeLaunchEvent.durationValue": "60 minutes",
        "HomeLaunchEvent.whereLabel": "Où",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Calendrier Apple",
        "HomeLaunchEvent.googleCalendar": "Google Agenda",
        "HomeLaunchEvent.toolkitLink": "Boîte à outils et ressources",
        "HomeLaunchEvent.shareLink": "Partager le lien",
        "HomeLaunchEvent.shareSubject": "Rejoignez la rencontre de lancement Coupe du Monde 2026",
        "HomeLaunchEvent.shareBody": "Inscrivez-vous à la rencontre de lancement de l'Activation Coupe du Monde 2026, lundi 1 juin à 9 h 00 ET :",
        "HomeLaunchEvent.calendarTitle": "Activation Coupe du Monde 2026 — Rencontre de lancement",
        "HomeLaunchEvent.calendarDescription": "Briefing de Jesus Film Project sur la boîte à outils Coupe du Monde 2026, la stratégie numérique et la manière d'activer votre région.",
        "HomeLaunchEvent.calendarRegisterLabel": "Inscription",
        "HomeLaunchEvent.calendarMeetingIdLabel": "ID de réunion",
        "Resources.eyebrow": "La boîte à outils",
        "Resources.tagline": "Chaque match, chaque nation, chaque âme.",
        "Resources.title": "Des ressources pour ce moment.",
        "Resources.description": "Tout est gratuit et conçu pour les 39 jours de la Coupe du Monde. Prenez ce qui convient à votre équipe et lancez-vous.",
        "Resources.categories.readyToUse.heading": "Prêts à utiliser",
        "Resources.categories.readyToUse.body": "Copiez, partagez, c'est fait. Aucune retouche nécessaire — envoyez-les aujourd'hui à des chercheurs ou à de nouveaux croyants.",
        "Resources.categories.customizable.heading": "Personnalisables",
        "Resources.categories.customizable.body": "Modèles, kits de doublage et fichiers sources — adaptez-les à votre langue, votre public et votre moment.",
        "Resources.categories.physicalKits.heading": "Kits physiques",
        "Resources.categories.physicalKits.body": "Des outils concrets pour les watch parties, l'évangélisation sportive et les équipes missionnaires sur le terrain.",
        "Resources.languageCountLabel": "langues",
        "Resources.openCta": "Ouvrir la ressource",
    },
    "de": {
        "Header.home": "Start",
        "Header.resources": "Ressourcen",
        "Header.menuLabel": "Menü",
        "Header.menuOpenLabel": "Menü öffnen",
        "Header.menuCloseLabel": "Menü schließen",
        "HomeLaunchVideo.eyebrow": "Ansehen",
        "HomeLaunchVideo.heading": "Das Herz dieser Aktivierung.",
        "HomeLaunchVideo.iframeTitle": "Startvideo zur Fußball-WM 2026",
        "HomeLaunchEvent.pill": "Live-Briefing",
        "HomeLaunchEvent.heading": "Lernt das Toolkit gemeinsam kennen.",
        "HomeLaunchEvent.body": "Eine Stunde. Die ganze Vision. Hört, wie Jesus Film Project, Partner und Verantwortliche aus aller Welt diesen Moment aktivieren — und nehmt den Startplan für eure Region mit.",
        "HomeLaunchEvent.cta": "Bei Zoom anmelden",
        "HomeLaunchEvent.freeCaption": "Kostenlos. Bestätigung und Teilnahmelink werden nach der Anmeldung von Zoom verschickt.",
        "HomeLaunchEvent.dateLabel": "Datum",
        "HomeLaunchEvent.dateValue": "Mo., 1. Juni 2026",
        "HomeLaunchEvent.timeLabel": "Uhrzeit",
        "HomeLaunchEvent.timeValue": "9:00 Uhr ET",
        "HomeLaunchEvent.durationLabel": "Dauer",
        "HomeLaunchEvent.durationValue": "60 Minuten",
        "HomeLaunchEvent.whereLabel": "Wo",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Apple Kalender",
        "HomeLaunchEvent.googleCalendar": "Google Kalender",
        "HomeLaunchEvent.toolkitLink": "Toolkit und Ressourcen",
        "HomeLaunchEvent.shareLink": "Link teilen",
        "HomeLaunchEvent.shareSubject": "Sei beim WM-2026-Startcall dabei",
        "HomeLaunchEvent.shareBody": "Melde dich zum Startcall der WM-2026-Aktivierung am Montag, 1. Juni um 9:00 Uhr ET an:",
        "HomeLaunchEvent.calendarTitle": "WM 2026 Aktivierung — Startcall",
        "HomeLaunchEvent.calendarDescription": "Live-Briefing von Jesus Film Project zum WM-2026-Toolkit, zur digitalen Strategie und zur Aktivierung deiner Region.",
        "HomeLaunchEvent.calendarRegisterLabel": "Anmeldung",
        "HomeLaunchEvent.calendarMeetingIdLabel": "Meeting-ID",
        "Resources.eyebrow": "Das Toolkit",
        "Resources.tagline": "Jedes Spiel, jede Nation, jede Seele.",
        "Resources.title": "Ressourcen für diesen Moment.",
        "Resources.description": "Alles ist kostenlos und für die 39 Tage der Weltmeisterschaft gemacht. Nehmt, was zu eurem Team passt, und legt los.",
        "Resources.categories.readyToUse.heading": "Sofort einsatzbereit",
        "Resources.categories.readyToUse.body": "Kopieren, teilen, fertig. Keine Bearbeitung nötig — heute schon an Suchende und neue Gläubige weitergeben.",
        "Resources.categories.customizable.heading": "Anpassbar",
        "Resources.categories.customizable.body": "Vorlagen, Synchronisations-Kits und Quelldateien — passt sie an eure Sprache, euer Publikum und euren Moment an.",
        "Resources.categories.physicalKits.heading": "Physische Kits",
        "Resources.categories.physicalKits.body": "Greifbare Tools für Watch Parties, Sport-Evangelisation und Missionsteams vor Ort.",
        "Resources.languageCountLabel": "Sprachen",
        "Resources.openCta": "Ressource öffnen",
    },
    "pt-BR": {
        "Header.home": "Início",
        "Header.resources": "Recursos",
        "Header.menuLabel": "Menu",
        "Header.menuOpenLabel": "Abrir menu",
        "Header.menuCloseLabel": "Fechar menu",
        "HomeLaunchVideo.eyebrow": "Assistir",
        "HomeLaunchVideo.heading": "Conheça o coração desta ativação.",
        "HomeLaunchVideo.iframeTitle": "Vídeo de lançamento Copa do Mundo 2026",
        "HomeLaunchEvent.pill": "Briefing ao vivo",
        "HomeLaunchEvent.heading": "Vamos passar pelo kit juntos.",
        "HomeLaunchEvent.body": "Uma hora. A visão inteira. Ouça como o Jesus Film Project, parceiros e líderes ministeriais do mundo todo estão ativando este momento — e saia com o plano de lançamento para a sua região.",
        "HomeLaunchEvent.cta": "Inscreva-se no Zoom",
        "HomeLaunchEvent.freeCaption": "Gratuito. Confirmação e link de acesso enviados pelo Zoom após a inscrição.",
        "HomeLaunchEvent.dateLabel": "Data",
        "HomeLaunchEvent.dateValue": "Seg, 1 de jun de 2026",
        "HomeLaunchEvent.timeLabel": "Horário",
        "HomeLaunchEvent.timeValue": "9h ET",
        "HomeLaunchEvent.durationLabel": "Duração",
        "HomeLaunchEvent.durationValue": "60 minutos",
        "HomeLaunchEvent.whereLabel": "Onde",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Calendário Apple",
        "HomeLaunchEvent.googleCalendar": "Google Agenda",
        "HomeLaunchEvent.toolkitLink": "Kit e recursos",
        "HomeLaunchEvent.shareLink": "Compartilhar link",
        "HomeLaunchEvent.shareSubject": "Participe da chamada de lançamento da Copa do Mundo 2026",
        "HomeLaunchEvent.shareBody": "Inscreva-se para a chamada de lançamento da Ativação Copa do Mundo 2026 na segunda-feira, 1 de junho às 9h ET:",
        "HomeLaunchEvent.calendarTitle": "Ativação Copa do Mundo 2026 — Chamada de lançamento",
        "HomeLaunchEvent.calendarDescription": "Briefing ao vivo do Jesus Film Project sobre o kit de evangelização da Copa do Mundo 2026, a estratégia digital e como ativar sua região.",
        "HomeLaunchEvent.calendarRegisterLabel": "Inscrição",
        "HomeLaunchEvent.calendarMeetingIdLabel": "ID da reunião",
        "Resources.eyebrow": "O kit",
        "Resources.tagline": "Cada jogo, cada nação, cada alma.",
        "Resources.title": "Recursos para este momento.",
        "Resources.description": "Tudo é gratuito e feito para os 39 dias da Copa. Use o que servir para a sua equipe.",
        "Resources.categories.readyToUse.heading": "Prontos para usar",
        "Resources.categories.readyToUse.body": "Copie, compartilhe, pronto. Sem edição — envie hoje para buscadores e novos crentes.",
        "Resources.categories.customizable.heading": "Personalizáveis",
        "Resources.categories.customizable.body": "Modelos, kits de dublagem e arquivos-fonte — adapte ao seu idioma, público e momento.",
        "Resources.categories.physicalKits.heading": "Kits físicos",
        "Resources.categories.physicalKits.body": "Ferramentas concretas para watch parties, evangelismo esportivo e equipes missionárias em campo.",
        "Resources.languageCountLabel": "idiomas",
        "Resources.openCta": "Abrir recurso",
    },
    "ru": {
        "Header.home": "Главная",
        "Header.resources": "Ресурсы",
        "Header.menuLabel": "Меню",
        "Header.menuOpenLabel": "Открыть меню",
        "Header.menuCloseLabel": "Закрыть меню",
        "HomeLaunchVideo.eyebrow": "Смотреть",
        "HomeLaunchVideo.heading": "Сердце этой активации.",
        "HomeLaunchVideo.iframeTitle": "Видео к запуску ЧМ-2026",
        "HomeLaunchEvent.pill": "Прямая встреча",
        "HomeLaunchEvent.heading": "Пройдём по ресурсам вместе.",
        "HomeLaunchEvent.body": "Один час. Вся картина. Услышьте, как Jesus Film Project, партнёры и служители по всему миру включаются в этот момент — и уйдите с планом запуска для вашего региона.",
        "HomeLaunchEvent.cta": "Зарегистрироваться в Zoom",
        "HomeLaunchEvent.freeCaption": "Бесплатно. После регистрации Zoom пришлёт подтверждение и ссылку.",
        "HomeLaunchEvent.dateLabel": "Дата",
        "HomeLaunchEvent.dateValue": "Пн, 1 июня 2026",
        "HomeLaunchEvent.timeLabel": "Время",
        "HomeLaunchEvent.timeValue": "9:00 ET",
        "HomeLaunchEvent.durationLabel": "Длительность",
        "HomeLaunchEvent.durationValue": "60 минут",
        "HomeLaunchEvent.whereLabel": "Где",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Календарь Apple",
        "HomeLaunchEvent.googleCalendar": "Google Календарь",
        "HomeLaunchEvent.toolkitLink": "Набор и ресурсы",
        "HomeLaunchEvent.shareLink": "Поделиться ссылкой",
        "HomeLaunchEvent.shareSubject": "Присоединяйтесь к встрече запуска ЧМ-2026",
        "HomeLaunchEvent.shareBody": "Регистрируйтесь на встречу запуска Активации ЧМ-2026 в понедельник 1 июня в 9:00 ET:",
        "HomeLaunchEvent.calendarTitle": "Активация ЧМ-2026 — Встреча запуска",
        "HomeLaunchEvent.calendarDescription": "Прямой брифинг Jesus Film Project о наборе для ЧМ-2026, цифровой стратегии и активации вашего региона.",
        "HomeLaunchEvent.calendarRegisterLabel": "Регистрация",
        "HomeLaunchEvent.calendarMeetingIdLabel": "ID встречи",
        "Resources.eyebrow": "Набор",
        "Resources.tagline": "Каждый матч, каждая нация, каждая душа.",
        "Resources.title": "Ресурсы для этого момента.",
        "Resources.description": "Всё бесплатно и создано для 39 дней Чемпионата мира. Берите то, что подойдёт вашей команде.",
        "Resources.categories.readyToUse.heading": "Готовы к использованию",
        "Resources.categories.readyToUse.body": "Скопируйте, поделитесь, готово. Никаких правок — отправляйте сегодня же ищущим и новым верующим.",
        "Resources.categories.customizable.heading": "Настраиваемые",
        "Resources.categories.customizable.body": "Шаблоны, наборы для дубляжа и исходники — адаптируйте к вашему языку, аудитории и моменту.",
        "Resources.categories.physicalKits.heading": "Физические наборы",
        "Resources.categories.physicalKits.body": "Реальные инструменты для совместных просмотров, спортивного благовестия и команд на местах.",
        "Resources.languageCountLabel": "языков",
        "Resources.openCta": "Открыть ресурс",
    },
    "zh-Hans": {
        "Header.home": "首页",
        "Header.resources": "资源",
        "Header.menuLabel": "菜单",
        "Header.menuOpenLabel": "打开菜单",
        "Header.menuCloseLabel": "关闭菜单",
        "HomeLaunchVideo.eyebrow": "观看",
        "HomeLaunchVideo.heading": "走进这次激活的核心。",
        "HomeLaunchVideo.iframeTitle": "2026 世界杯启动视频",
        "HomeLaunchEvent.pill": "现场简报",
        "HomeLaunchEvent.heading": "我们一起走一遍工具包。",
        "HomeLaunchEvent.body": "一小时。完整的异象。听听 Jesus Film Project、合作伙伴以及全球各地的事工领袖如何把握这个时刻——并带走专属于你所在地区的启动计划。",
        "HomeLaunchEvent.cta": "在 Zoom 上注册",
        "HomeLaunchEvent.freeCaption": "免费。注册后 Zoom 会发送确认信和加入链接。",
        "HomeLaunchEvent.dateLabel": "日期",
        "HomeLaunchEvent.dateValue": "2026 年 6 月 1 日(周一)",
        "HomeLaunchEvent.timeLabel": "时间",
        "HomeLaunchEvent.timeValue": "美东时间 上午 9:00",
        "HomeLaunchEvent.durationLabel": "时长",
        "HomeLaunchEvent.durationValue": "60 分钟",
        "HomeLaunchEvent.whereLabel": "地点",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Apple 日历",
        "HomeLaunchEvent.googleCalendar": "Google 日历",
        "HomeLaunchEvent.toolkitLink": "工具包与资源",
        "HomeLaunchEvent.shareLink": "分享链接",
        "HomeLaunchEvent.shareSubject": "一起加入 2026 世界杯启动呼召",
        "HomeLaunchEvent.shareBody": "报名参加 2026 世界杯激活启动呼召,周一 6 月 1 日 美东时间上午 9:00:",
        "HomeLaunchEvent.calendarTitle": "2026 世界杯激活 — 启动呼召",
        "HomeLaunchEvent.calendarDescription": "Jesus Film Project 关于 2026 世界杯外展工具包、数字策略以及如何激活你所在地区的现场简报。",
        "HomeLaunchEvent.calendarRegisterLabel": "报名",
        "HomeLaunchEvent.calendarMeetingIdLabel": "会议 ID",
        "Resources.eyebrow": "工具包",
        "Resources.tagline": "每一场比赛,每一个国家,每一个灵魂。",
        "Resources.title": "为此刻准备的资源。",
        "Resources.description": "所有内容免费,专为世界杯 39 天而设计。选用适合你团队的内容,开始行动。",
        "Resources.categories.readyToUse.heading": "即拿即用",
        "Resources.categories.readyToUse.body": "复制、分享、搞定。无需编辑——今天就可以发给寻道者和新信徒。",
        "Resources.categories.customizable.heading": "可定制",
        "Resources.categories.customizable.body": "模板、配音包和源文件——按语言、受众和时机进行调整。",
        "Resources.categories.physicalKits.heading": "实物礼包",
        "Resources.categories.physicalKits.body": "用于观赛聚会、运动福音和一线宣教队的实物工具。",
        "Resources.languageCountLabel": "种语言",
        "Resources.openCta": "打开资源",
    },
    "id": {
        "Header.home": "Beranda",
        "Header.resources": "Sumber Daya",
        "Header.menuLabel": "Menu",
        "Header.menuOpenLabel": "Buka menu",
        "Header.menuCloseLabel": "Tutup menu",
        "HomeLaunchVideo.eyebrow": "Tonton",
        "HomeLaunchVideo.heading": "Lihat inti dari aktivasi ini.",
        "HomeLaunchVideo.iframeTitle": "Video peluncuran Piala Dunia 2026",
        "HomeLaunchEvent.pill": "Briefing langsung",
        "HomeLaunchEvent.heading": "Mari telusuri perlengkapan ini bersama.",
        "HomeLaunchEvent.body": "Satu jam. Seluruh visi. Dengarkan bagaimana Jesus Film Project, mitra, dan para pemimpin pelayanan di seluruh dunia mengaktifkan momen ini — dan pulanglah dengan rencana peluncuran untuk wilayah Anda.",
        "HomeLaunchEvent.cta": "Daftar di Zoom",
        "HomeLaunchEvent.freeCaption": "Gratis. Konfirmasi dan tautan bergabung dikirim oleh Zoom setelah Anda mendaftar.",
        "HomeLaunchEvent.dateLabel": "Tanggal",
        "HomeLaunchEvent.dateValue": "Sen, 1 Jun 2026",
        "HomeLaunchEvent.timeLabel": "Waktu",
        "HomeLaunchEvent.timeValue": "9:00 ET",
        "HomeLaunchEvent.durationLabel": "Durasi",
        "HomeLaunchEvent.durationValue": "60 menit",
        "HomeLaunchEvent.whereLabel": "Tempat",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Kalender Apple",
        "HomeLaunchEvent.googleCalendar": "Google Calendar",
        "HomeLaunchEvent.toolkitLink": "Perlengkapan dan sumber daya",
        "HomeLaunchEvent.shareLink": "Bagikan tautan",
        "HomeLaunchEvent.shareSubject": "Ikuti panggilan peluncuran Piala Dunia 2026",
        "HomeLaunchEvent.shareBody": "Daftar untuk panggilan peluncuran Aktivasi Piala Dunia 2026 pada Senin, 1 Juni pukul 9:00 ET:",
        "HomeLaunchEvent.calendarTitle": "Aktivasi Piala Dunia 2026 — Panggilan peluncuran",
        "HomeLaunchEvent.calendarDescription": "Briefing langsung Jesus Film Project tentang perlengkapan penjangkauan Piala Dunia 2026, strategi digital, dan cara mengaktifkan wilayah Anda.",
        "HomeLaunchEvent.calendarRegisterLabel": "Pendaftaran",
        "HomeLaunchEvent.calendarMeetingIdLabel": "ID rapat",
        "Resources.eyebrow": "Perlengkapan",
        "Resources.tagline": "Setiap pertandingan, setiap bangsa, setiap jiwa.",
        "Resources.title": "Sumber daya untuk momen ini.",
        "Resources.description": "Semua gratis dan dirancang untuk 39 hari Piala Dunia. Ambil yang cocok untuk tim Anda dan jalankan.",
        "Resources.categories.readyToUse.heading": "Siap pakai",
        "Resources.categories.readyToUse.body": "Salin, bagikan, selesai. Tanpa pengeditan — kirim hari ini juga kepada pencari dan orang percaya baru.",
        "Resources.categories.customizable.heading": "Dapat disesuaikan",
        "Resources.categories.customizable.body": "Templat, kit sulih suara, dan berkas sumber — sesuaikan dengan bahasa, audiens, dan momen Anda.",
        "Resources.categories.physicalKits.heading": "Kit fisik",
        "Resources.categories.physicalKits.body": "Alat nyata untuk watch party, penginjilan olahraga, dan tim pelayanan di lapangan.",
        "Resources.languageCountLabel": "bahasa",
        "Resources.openCta": "Buka sumber daya",
    },
    "ar": {
        "Header.home": "الرئيسية",
        "Header.resources": "الموارد",
        "Header.menuLabel": "القائمة",
        "Header.menuOpenLabel": "فتح القائمة",
        "Header.menuCloseLabel": "إغلاق القائمة",
        "HomeLaunchVideo.eyebrow": "شاهد",
        "HomeLaunchVideo.heading": "اقترب من قلب هذه الفعالية.",
        "HomeLaunchVideo.iframeTitle": "فيديو انطلاق كأس العالم 2026",
        "HomeLaunchEvent.pill": "إحاطة مباشرة",
        "HomeLaunchEvent.heading": "نتعرّف على الأدوات معًا.",
        "HomeLaunchEvent.body": "ساعة واحدة. الرؤية كاملة. اسمع كيف يُفعِّل مشروع جيسس فيلم وشركاؤه وقادة الخدمة حول العالم هذه اللحظة — واخرج بخطة الإطلاق لمنطقتك.",
        "HomeLaunchEvent.cta": "سجّل في Zoom",
        "HomeLaunchEvent.freeCaption": "مجانًا. سيرسل Zoom التأكيد ورابط الانضمام بعد التسجيل.",
        "HomeLaunchEvent.dateLabel": "التاريخ",
        "HomeLaunchEvent.dateValue": "الإثنين، 1 يونيو 2026",
        "HomeLaunchEvent.timeLabel": "الوقت",
        "HomeLaunchEvent.timeValue": "9:00 صباحًا بتوقيت شرق أمريكا",
        "HomeLaunchEvent.durationLabel": "المدة",
        "HomeLaunchEvent.durationValue": "60 دقيقة",
        "HomeLaunchEvent.whereLabel": "المكان",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "تقويم Apple",
        "HomeLaunchEvent.googleCalendar": "تقويم Google",
        "HomeLaunchEvent.toolkitLink": "الأدوات والموارد",
        "HomeLaunchEvent.shareLink": "مشاركة الرابط",
        "HomeLaunchEvent.shareSubject": "انضم إلى لقاء انطلاق كأس العالم 2026",
        "HomeLaunchEvent.shareBody": "سجّل لحضور لقاء انطلاق تفعيل كأس العالم 2026 يوم الإثنين 1 يونيو الساعة 9:00 صباحًا بتوقيت شرق أمريكا:",
        "HomeLaunchEvent.calendarTitle": "تفعيل كأس العالم 2026 — لقاء الانطلاق",
        "HomeLaunchEvent.calendarDescription": "إحاطة مباشرة من مشروع جيسس فيلم حول أدوات كأس العالم 2026، والاستراتيجية الرقمية، وكيفية تفعيل منطقتك.",
        "HomeLaunchEvent.calendarRegisterLabel": "التسجيل",
        "HomeLaunchEvent.calendarMeetingIdLabel": "معرّف الاجتماع",
        "Resources.eyebrow": "الأدوات",
        "Resources.tagline": "كل مباراة، كل أمة، كل نفس.",
        "Resources.title": "موارد لهذه اللحظة.",
        "Resources.description": "كل شيء مجاني ومصمم لـ39 يومًا من كأس العالم. خذ ما يناسب فريقك وابدأ.",
        "Resources.categories.readyToUse.heading": "جاهزة للاستخدام",
        "Resources.categories.readyToUse.body": "انسخ، شارك، انتهيت. لا حاجة للتعديل — أرسلها اليوم للباحثين والمؤمنين الجدد.",
        "Resources.categories.customizable.heading": "قابلة للتخصيص",
        "Resources.categories.customizable.body": "قوالب وأطقم دبلجة وملفات مصدرية — كيِّفها مع لغتك وجمهورك ولحظتك.",
        "Resources.categories.physicalKits.heading": "أطقم فعلية",
        "Resources.categories.physicalKits.body": "أدوات ملموسة للقاءات المشاهدة، والتبشير الرياضي، وفرق الخدمة على الأرض.",
        "Resources.languageCountLabel": "لغة",
        "Resources.openCta": "افتح المورد",
    },
    "hi": {
        "Header.home": "होम",
        "Header.resources": "संसाधन",
        "Header.menuLabel": "मेनू",
        "Header.menuOpenLabel": "मेनू खोलें",
        "Header.menuCloseLabel": "मेनू बंद करें",
        "HomeLaunchVideo.eyebrow": "देखें",
        "HomeLaunchVideo.heading": "इस सक्रियता का दिल देखिए।",
        "HomeLaunchVideo.iframeTitle": "विश्व कप 2026 लॉन्च वीडियो",
        "HomeLaunchEvent.pill": "लाइव ब्रीफिंग",
        "HomeLaunchEvent.heading": "मिलकर इस टूलकिट को समझें।",
        "HomeLaunchEvent.body": "एक घंटा। पूरी दृष्टि। सुनिए कि कैसे Jesus Film Project, सहयोगी और दुनिया भर के सेवा-नेता इस पल को सक्रिय कर रहे हैं — और अपने क्षेत्र के लिए लॉन्च प्लान लेकर लौटिए।",
        "HomeLaunchEvent.cta": "Zoom पर रजिस्टर करें",
        "HomeLaunchEvent.freeCaption": "मुफ़्त। रजिस्टर करने पर Zoom पुष्टि और जॉइन लिंक भेजेगा।",
        "HomeLaunchEvent.dateLabel": "तारीख़",
        "HomeLaunchEvent.dateValue": "सोम, 1 जून 2026",
        "HomeLaunchEvent.timeLabel": "समय",
        "HomeLaunchEvent.timeValue": "सुबह 9:00 ET",
        "HomeLaunchEvent.durationLabel": "अवधि",
        "HomeLaunchEvent.durationValue": "60 मिनट",
        "HomeLaunchEvent.whereLabel": "कहाँ",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Apple कैलेंडर",
        "HomeLaunchEvent.googleCalendar": "Google कैलेंडर",
        "HomeLaunchEvent.toolkitLink": "टूलकिट और संसाधन",
        "HomeLaunchEvent.shareLink": "लिंक शेयर करें",
        "HomeLaunchEvent.shareSubject": "विश्व कप 2026 लॉन्च कॉल में जुड़ें",
        "HomeLaunchEvent.shareBody": "विश्व कप 2026 सक्रियण लॉन्च कॉल के लिए सोमवार, 1 जून, सुबह 9:00 ET पर रजिस्टर करें:",
        "HomeLaunchEvent.calendarTitle": "विश्व कप 2026 सक्रियण — लॉन्च कॉल",
        "HomeLaunchEvent.calendarDescription": "Jesus Film Project की लाइव ब्रीफिंग विश्व कप 2026 आउटरीच टूलकिट, डिजिटल रणनीति और अपने क्षेत्र को सक्रिय करने पर।",
        "HomeLaunchEvent.calendarRegisterLabel": "रजिस्टर",
        "HomeLaunchEvent.calendarMeetingIdLabel": "मीटिंग ID",
        "Resources.eyebrow": "टूलकिट",
        "Resources.tagline": "हर मैच, हर देश, हर आत्मा।",
        "Resources.title": "इस पल के लिए संसाधन।",
        "Resources.description": "सब कुछ मुफ़्त है और विश्व कप के 39 दिनों के लिए बनाया गया है। जो आपकी टीम के लिए सही हो, ले लीजिए।",
        "Resources.categories.readyToUse.heading": "तैयार-उपयोग के लिए",
        "Resources.categories.readyToUse.body": "कॉपी, शेयर, हो गया। कोई बदलाव नहीं — आज ही जिज्ञासुओं और नए विश्वासियों को भेजें।",
        "Resources.categories.customizable.heading": "अनुकूलन योग्य",
        "Resources.categories.customizable.body": "टेम्पलेट, डबिंग किट और स्रोत फ़ाइलें — अपनी भाषा, दर्शक और समय के अनुसार ढालिए।",
        "Resources.categories.physicalKits.heading": "भौतिक किट",
        "Resources.categories.physicalKits.body": "वॉच पार्टी, स्पोर्ट्स इवेंजेलिज्म और ज़मीन पर सेवा-दलों के लिए ठोस उपकरण।",
        "Resources.languageCountLabel": "भाषाएँ",
        "Resources.openCta": "संसाधन खोलें",
    },
    "bn": {
        "Header.home": "হোম",
        "Header.resources": "রিসোর্স",
        "Header.menuLabel": "মেনু",
        "Header.menuOpenLabel": "মেনু খুলুন",
        "Header.menuCloseLabel": "মেনু বন্ধ করুন",
        "HomeLaunchVideo.eyebrow": "দেখুন",
        "HomeLaunchVideo.heading": "এই সক্রিয়তার হৃদয় দেখুন।",
        "HomeLaunchVideo.iframeTitle": "বিশ্বকাপ 2026 লঞ্চ ভিডিও",
        "HomeLaunchEvent.pill": "লাইভ ব্রিফিং",
        "HomeLaunchEvent.heading": "একসাথে টুলকিট ঘুরে দেখি।",
        "HomeLaunchEvent.body": "এক ঘণ্টা। পূর্ণ দৃষ্টি। শুনুন কীভাবে Jesus Film Project, পার্টনাররা এবং সারা পৃথিবীর পরিচর্যা-নেতারা এই মুহূর্তকে সক্রিয় করছেন — এবং নিজের অঞ্চলের জন্য লঞ্চ পরিকল্পনা নিয়ে ফিরে যান।",
        "HomeLaunchEvent.cta": "Zoom-এ রেজিস্টার করুন",
        "HomeLaunchEvent.freeCaption": "ফ্রি। রেজিস্টার করলে Zoom কনফার্মেশন ও জয়েন লিঙ্ক পাঠাবে।",
        "HomeLaunchEvent.dateLabel": "তারিখ",
        "HomeLaunchEvent.dateValue": "সোম, ১ জুন ২০২৬",
        "HomeLaunchEvent.timeLabel": "সময়",
        "HomeLaunchEvent.timeValue": "সকাল ৯:০০ ET",
        "HomeLaunchEvent.durationLabel": "সময়কাল",
        "HomeLaunchEvent.durationValue": "৬০ মিনিট",
        "HomeLaunchEvent.whereLabel": "কোথায়",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Apple ক্যালেন্ডার",
        "HomeLaunchEvent.googleCalendar": "Google ক্যালেন্ডার",
        "HomeLaunchEvent.toolkitLink": "টুলকিট ও রিসোর্স",
        "HomeLaunchEvent.shareLink": "লিঙ্ক শেয়ার",
        "HomeLaunchEvent.shareSubject": "বিশ্বকাপ ২০২৬ লঞ্চ কলে যোগ দিন",
        "HomeLaunchEvent.shareBody": "সোমবার ১ জুন সকাল ৯:০০ ET-তে বিশ্বকাপ ২০২৬ অ্যাক্টিভেশন লঞ্চ কলের জন্য রেজিস্টার করুন:",
        "HomeLaunchEvent.calendarTitle": "বিশ্বকাপ ২০২৬ অ্যাক্টিভেশন — লঞ্চ কল",
        "HomeLaunchEvent.calendarDescription": "Jesus Film Project থেকে বিশ্বকাপ ২০২৬ আউটরিচ টুলকিট, ডিজিটাল কৌশল এবং নিজের অঞ্চল সক্রিয় করার লাইভ ব্রিফিং।",
        "HomeLaunchEvent.calendarRegisterLabel": "রেজিস্ট্রেশন",
        "HomeLaunchEvent.calendarMeetingIdLabel": "মিটিং ID",
        "Resources.eyebrow": "টুলকিট",
        "Resources.tagline": "প্রতিটি ম্যাচ, প্রতিটি জাতি, প্রতিটি প্রাণ।",
        "Resources.title": "এই মুহূর্তের জন্য রিসোর্স।",
        "Resources.description": "সবকিছু ফ্রি এবং বিশ্বকাপের ৩৯ দিনের জন্য তৈরি। যা আপনার টিমের জন্য মানানসই তা নিয়ে শুরু করুন।",
        "Resources.categories.readyToUse.heading": "ব্যবহারের জন্য প্রস্তুত",
        "Resources.categories.readyToUse.body": "কপি, শেয়ার, শেষ। কোনো এডিট নয় — আজই অনুসন্ধানী ও নতুন বিশ্বাসীদের পাঠান।",
        "Resources.categories.customizable.heading": "কাস্টমাইজযোগ্য",
        "Resources.categories.customizable.body": "টেমপ্লেট, ডাবিং কিট ও সোর্স ফাইল — নিজের ভাষা, দর্শক ও সময়ের সাথে মানিয়ে নিন।",
        "Resources.categories.physicalKits.heading": "শারীরিক কিট",
        "Resources.categories.physicalKits.body": "ওয়াচ পার্টি, স্পোর্টস ইভেঞ্জেলিজম এবং মাঠে কাজ করা দলগুলোর জন্য বাস্তব উপকরণ।",
        "Resources.languageCountLabel": "ভাষা",
        "Resources.openCta": "রিসোর্স খুলুন",
    },
    "ur": {
        "Header.home": "ہوم",
        "Header.resources": "وسائل",
        "Header.menuLabel": "مینو",
        "Header.menuOpenLabel": "مینو کھولیں",
        "Header.menuCloseLabel": "مینو بند کریں",
        "HomeLaunchVideo.eyebrow": "دیکھیں",
        "HomeLaunchVideo.heading": "اِس فعالی کے دل کو دیکھیں۔",
        "HomeLaunchVideo.iframeTitle": "ورلڈ کپ 2026 لانچ ویڈیو",
        "HomeLaunchEvent.pill": "براہ راست بریفنگ",
        "HomeLaunchEvent.heading": "آئیے مل کر ٹول کٹ دیکھیں۔",
        "HomeLaunchEvent.body": "ایک گھنٹہ۔ پوری بصیرت۔ سنیں کہ Jesus Film Project، شراکت دار اور دنیا بھر کے خدمت کے رہنما اِس لمحے کو کیسے فعال کر رہے ہیں — اور اپنے علاقے کے لیے لانچ پلان لے کر واپس جائیں۔",
        "HomeLaunchEvent.cta": "Zoom پر رجسٹر کریں",
        "HomeLaunchEvent.freeCaption": "مفت۔ رجسٹر کرنے کے بعد Zoom تصدیق اور جوائن لنک بھیجے گا۔",
        "HomeLaunchEvent.dateLabel": "تاریخ",
        "HomeLaunchEvent.dateValue": "پیر، 1 جون 2026",
        "HomeLaunchEvent.timeLabel": "وقت",
        "HomeLaunchEvent.timeValue": "صبح 9:00 ET",
        "HomeLaunchEvent.durationLabel": "دورانیہ",
        "HomeLaunchEvent.durationValue": "60 منٹ",
        "HomeLaunchEvent.whereLabel": "کہاں",
        "HomeLaunchEvent.whereValue": "Zoom",
        "HomeLaunchEvent.addToCalendar": "Apple کیلنڈر",
        "HomeLaunchEvent.googleCalendar": "Google کیلنڈر",
        "HomeLaunchEvent.toolkitLink": "ٹول کٹ اور وسائل",
        "HomeLaunchEvent.shareLink": "لنک شیئر کریں",
        "HomeLaunchEvent.shareSubject": "ورلڈ کپ 2026 لانچ کال میں شامل ہوں",
        "HomeLaunchEvent.shareBody": "پیر، 1 جون، صبح 9:00 ET پر ورلڈ کپ 2026 ایکٹیویشن لانچ کال کے لیے رجسٹر کریں:",
        "HomeLaunchEvent.calendarTitle": "ورلڈ کپ 2026 ایکٹیویشن — لانچ کال",
        "HomeLaunchEvent.calendarDescription": "Jesus Film Project کی براہ راست بریفنگ ورلڈ کپ 2026 آؤٹریچ ٹول کٹ، ڈیجیٹل حکمت عملی اور اپنے علاقے کو فعال کرنے کے بارے میں۔",
        "HomeLaunchEvent.calendarRegisterLabel": "رجسٹریشن",
        "HomeLaunchEvent.calendarMeetingIdLabel": "میٹنگ ID",
        "Resources.eyebrow": "ٹول کٹ",
        "Resources.tagline": "ہر میچ، ہر قوم، ہر روح۔",
        "Resources.title": "اِس لمحے کے لیے وسائل۔",
        "Resources.description": "سب کچھ مفت ہے اور ورلڈ کپ کے 39 دنوں کے لیے بنایا گیا ہے۔ جو آپ کی ٹیم کے لیے موزوں ہو لے لیں اور آغاز کریں۔",
        "Resources.categories.readyToUse.heading": "استعمال کے لیے تیار",
        "Resources.categories.readyToUse.body": "کاپی، شیئر، ختم۔ کوئی ترمیم نہیں — آج ہی متلاشیوں اور نئے ایمان داروں کو بھیجیں۔",
        "Resources.categories.customizable.heading": "حسبِ ضرورت",
        "Resources.categories.customizable.body": "ٹیمپلیٹس، ڈبنگ کٹ اور سورس فائلیں — اپنی زبان، سامعین اور لمحے کے مطابق ڈھالیں۔",
        "Resources.categories.physicalKits.heading": "طبعی کِٹس",
        "Resources.categories.physicalKits.body": "واچ پارٹیز، اسپورٹس ایوینجلزم اور میدانی خدمت ٹیموں کے لیے ٹھوس آلات۔",
        "Resources.languageCountLabel": "زبانیں",
        "Resources.openCta": "وسیلہ کھولیں",
    },
}


def deep_set(d: dict, dotted: str, value: str) -> None:
    parts = dotted.split(".")
    cur = d
    for p in parts[:-1]:
        cur = cur.setdefault(p, {})
    cur[parts[-1]] = value


def main() -> None:
    for locale, entries in TRANSLATIONS.items():
        path = MESSAGES / f"{locale}.json"
        with open(path, encoding="utf-8") as f:
            d = json.load(f)
        for k, v in entries.items():
            deep_set(d, k, v)
        with open(path, "w", encoding="utf-8") as f:
            json.dump(d, f, ensure_ascii=False, indent=2)
            f.write("\n")
        print(f"  ✓ {locale} ({len(entries)} keys)")


if __name__ == "__main__":
    main()
